name: CI with Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-with-cache:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up uv
      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      # 3️⃣ Create virtual environment
      - name: Create virtual environment
        run: uv venv

      # 4️⃣ Cache uv dependencies
      - name: Cache uv dependencies
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: cache-4a7e659
          cache-dependency-path: ''  # prevents warnings about missing files

      # 5️⃣ Install dependencies from requirements.txt
      - name: Install dependencies
        run: uv pip install -r $GITHUB_WORKSPACE/requirements.txt

      # 6️⃣ Prime cache message
      - name: Prime cache
        run: |
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Dependencies were installed and cache will be saved."
          fi
